# Generated by Django 6.0 on 2026-02-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0002_orderitem_alter_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Investigating', 'Investigating'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Received', max_length=20),
        ),
    ]
