# Generated by Django 6.0 on 2026-02-25 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0004_remove_orderitem_order_remove_orderitem_item_report_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stall', models.CharField(choices=[('Stall 1', 'Stall 1'), ('Stall 2', 'Stall 2'), ('Stall 3', 'Stall 3')], max_length=100)),
                ('rating', models.IntegerField(default=5)),
                ('food_name', models.CharField(max_length=200)),
                ('feedback', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
