# Generated by Django 6.0 on 2026-02-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0006_suggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='user',
        ),
        migrations.AlterField(
            model_name='rating',
            name='stall',
            field=models.CharField(choices=[("Maren's Food Cart", "Maren's Food Cart"), ('Rhoxy Canteen', 'Rhoxy Canteen'), ('M.D Mangubat Canteen', 'M.D Mangubat Canteen'), ('Stall 4', 'Stall 4'), ('Goldfranz Canteen', 'Goldfranz Canteen'), ('K-Pop House', 'K-Pop House'), ('kCairo Johns Food Hub', 'kCairo Johns Food Hub'), ('Tiger Crunch', 'Tiger Crunch')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='stall',
            field=models.CharField(choices=[("Maren's Food Cart", "Maren's Food Cart"), ('Rhoxy Canteen', 'Rhoxy Canteen'), ('M.D Mangubat Canteen', 'M.D Mangubat Canteen'), ('Stall 4', 'Stall 4'), ('Goldfranz Canteen', 'Goldfranz Canteen'), ('K-Pop House', 'K-Pop House'), ('kCairo Johns Food Hub', 'kCairo Johns Food Hub'), ('Tiger Crunch', 'Tiger Crunch')], max_length=100),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='stall',
            field=models.CharField(choices=[("Maren's Food Cart", "Maren's Food Cart"), ('Rhoxy Canteen', 'Rhoxy Canteen'), ('M.D Mangubat Canteen', 'M.D Mangubat Canteen'), ('Stall 4', 'Stall 4'), ('Goldfranz Canteen', 'Goldfranz Canteen'), ('K-Pop House', 'K-Pop House'), ('kCairo Johns Food Hub', 'kCairo Johns Food Hub'), ('Tiger Crunch', 'Tiger Crunch')], max_length=100),
        ),
    ]
