# Generated by Django 6.0.2 on 2026-02-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0008_rating_user_suggestion_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rating',
            name='stall',
            field=models.CharField(choices=[("Maren's Food Cart", "Maren's Food Cart"), ('Rhoxy Canteen', 'Rhoxy Canteen'), ('M.D Mangubat Canteen', 'M.D Mangubat Canteen'), ('Mann Food House', 'Mann Food House'), ('Goldfranz Canteen', 'Goldfranz Canteen'), ('K-Pop House', 'K-Pop House'), ('kCairo Johns Food Hub', 'kCairo Johns Food Hub'), ('Tiger Crunch', 'Tiger Crunch')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='stall',
            field=models.CharField(choices=[("Maren's Food Cart", "Maren's Food Cart"), ('Rhoxy Canteen', 'Rhoxy Canteen'), ('M.D Mangubat Canteen', 'M.D Mangubat Canteen'), ('Mann Food House', 'Mann Food House'), ('Goldfranz Canteen', 'Goldfranz Canteen'), ('K-Pop House', 'K-Pop House'), ('kCairo Johns Food Hub', 'kCairo Johns Food Hub'), ('Tiger Crunch', 'Tiger Crunch')], max_length=100),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='stall',
            field=models.CharField(choices=[("Maren's Food Cart", "Maren's Food Cart"), ('Rhoxy Canteen', 'Rhoxy Canteen'), ('M.D Mangubat Canteen', 'M.D Mangubat Canteen'), ('Mann Food House', 'Mann Food House'), ('Goldfranz Canteen', 'Goldfranz Canteen'), ('K-Pop House', 'K-Pop House'), ('kCairo Johns Food Hub', 'kCairo Johns Food Hub'), ('Tiger Crunch', 'Tiger Crunch')], max_length=100),
        ),
    ]
