# Generated by Django 6.0.2 on 2026-02-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0009_report_is_read_alter_rating_stall_alter_report_stall_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
